# Generated by Django 2.2 on 2020-06-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toot',
            options={'ordering': ['-id']},
        ),
    ]
