# Generated by Django 2.2 on 2020-06-26 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toots', '0004_auto_20200626_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='toot',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toots.Toot'),
        ),
    ]
