# Generated by Django 2.2 on 2020-07-01 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toots', '0005_toot_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toot',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toots.Toot'),
        ),
    ]
