# Generated by Django 2.2 on 2020-07-03 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toots', '0007_auto_20200704_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toot',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='toots.Toot'),
        ),
    ]
