# Generated by Django 2.2 on 2020-07-03 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toots', '0008_auto_20200704_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toot',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_toots', through='toots.TootLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
